HistoricalMarketSystem:
  tc:             0.01
  inventory_risk: 0.001
Historical_EM_Simulator:
  N_steps :     1000
  step_size:    0.001
discount_factor: 0.99
GaussianPDFModelCus:
  n_hidden_layers: 4
  scale_factor:    50
  dim_hidden:      5
  std:             0.05
  action_bounds_l: 0.
  action_bounds_u: 1.5
ModelPerceptron:
  dim_output:      1
  dim_hidden:      5
  n_hidden_layers: 5
OptimizerSampledCritic:
  n_epochs: 15
  opt_options:
    lr:     0.045
OptimizerSampledPolicy:
  opt_options:
    lr:     0.045
Critic:
  td_n:     8
MonteCarloSimulationScenarioTrain:
  N_episodes:   6
  N_iterations: 14
MonteCarloSimulationScenarioTest:
  N_episodes:   40
  N_iterations: 1